import logging

LOG_LEVEL = logging.INFO
CHARACTER_RADIUS = 10
CHARACTER_SPEED = 0.05
HITBOX_OFFSET_X = 16
HITBOX_OFFSET_Y = 20
SCREEN_WIDTH = 640
SCREEN_HEIGHT = 480
FPS = 60
SPRITE_SIZE = 32
NAVIGATION_TOLERANCE = 5
CIRCLE_EDGES = 8                # number of edges to give a circle when creating navmesh